spring:
  application:
    name: CipherChat
  datasource:
    url: jdbc:postgresql://localhost:5432/cipher_chat
    username: postgres
    password: 111
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  devtools:
    restart:
      poll-interval: 2s
      quiet-period: 1s